Repository drupal-ukraine/dcamp-site, pull requests merged in 2019-02, with the labels that each got.

#20 DCK-XXX: Update README file
  .docksal/docksal.env
  README.md
Labels: Need Review

#27 DCK-12: Update spaces between elements in html widget
  .docksal/commands/init
  .docksal/commands/rebuild
  docroot/themes/custom/dckyiv/style/scss/components/_paragraph--html-widget.scss
Labels: Need Work

#35 Update Readme
  README.md
Labels: Need Review

#38 DCK-15
  docroot/themes/custom/dckyiv/style/scss/base/_forms.scss
Labels: Need Work, 🏷 FrontEnd

#41 Add lang icon + change logo
  config/sync/core.base_field_override.commerce_product.default.title.yml
  config/sync/core.base_field_override.menu_link_content.menu_link_content.description.yml
  config/sync/core.base_field_override.menu_link_content.menu_link_content.title.yml
  config/sync/field.field.commerce_product.default.body.yml
  config/sync/field.field.media.image.field_media_image.yml
  config/sync/field.field.node.article.field_image.yml
  config/sync/field.field.user.user.user_picture.yml
  config/sync/language.content_settings.commerce_product.default.yml
  config/sync/language.content_settings.menu_link_content.menu_link_content.yml
  config/sync/language.types.yml
  config/sync/system.site.yml
  docroot/themes/custom/dckyiv/android-chrome-192x192.png
  docroot/themes/custom/dckyiv/android-chrome-512x512.png
  docroot/themes/custom/dckyiv/apple-touch-icon.png
  docroot/themes/custom/dckyiv/favicon-16x16.png
  docroot/themes/custom/dckyiv/favicon-32x32.png
  docroot/themes/custom/dckyiv/favicon.ico
  docroot/themes/custom/dckyiv/style/scss/base/_layout.scss
  docroot/themes/custom/dckyiv/style/scss/components/_footer.scss
  docroot/themes/custom/dckyiv/style/scss/components/_header.scss
  docroot/themes/custom/dckyiv/templates/layout/html.html.twig
  docroot/themes/custom/dckyiv/templates/misc/links--language-block.html.twig
Labels: Need Review, 🏷 FrontEnd

#49 DCK-18: Add style for complete order page
  composer.json
  composer.lock
  config/sync/core.entity_view_display.paragraph.hero_countdown.default.yml
  config/sync/views.view.camp_tickets.yml
  docroot/modules/custom/dckyiv_user/dckyiv_user.links.task.yml
  docroot/modules/custom/dckyiv_user/src/Form/DCKUserRegisterForm.php
  docroot/themes/custom/dckyiv/images/dckyiv_white_logo.png
  docroot/themes/custom/dckyiv/style/scss/base/_drupal.scss
  docroot/themes/custom/dckyiv/style/scss/base/_layout.scss
  docroot/themes/custom/dckyiv/style/scss/components/_commerce-checkout-completion.scss
  docroot/themes/custom/dckyiv/style/scss/components/_header.scss
  docroot/themes/custom/dckyiv/style/scss/components/_list-as-dropdown.scss
  docroot/themes/custom/dckyiv/style/scss/components/_user_login_form.scss
  docroot/themes/custom/dckyiv/templates/commerce/commerce-checkout-completion-message.html.twig
  docroot/themes/custom/dckyiv/templates/layout/page--user.html.twig
  docroot/themes/custom/dckyiv/templates/layout/page.html.twig
Labels: Need Review, 🏷 FrontEnd

#52 DCK-19: Fix current main bugs with style
  docroot/modules/custom/dckyiv_iconset/dckyiv_iconset.info.yml
  docroot/modules/custom/dckyiv_iconset/src/Plugin/SocialMediaLinks/Iconset/DCKyivIconset.php
  docroot/themes/custom/dckyiv/style/scss/base/_drupal.scss
  docroot/themes/custom/dckyiv/style/scss/base/_layout.scss
  docroot/themes/custom/dckyiv/style/scss/components/_commerce-cart-form.scss
  docroot/themes/custom/dckyiv/style/scss/components/_commerce-product-full.scss
  docroot/themes/custom/dckyiv/style/scss/components/_commerce-product-in-modal.scss
  docroot/themes/custom/dckyiv/style/scss/components/_footer.scss
  docroot/themes/custom/dckyiv/style/scss/components/_header.scss
  docroot/themes/custom/dckyiv/style/scss/components/_list-as-dropdown.scss
  docroot/themes/custom/dckyiv/style/scss/components/_paragraph--camp-products.scss
  docroot/themes/custom/dckyiv/style/scss/components/_paragraph--contacts.scss
  docroot/themes/custom/dckyiv/templates/commerce/commerce-product--full.html.twig
  docroot/themes/custom/dckyiv/templates/layout/page--user.html.twig
Labels: Need Review, 🏷 FrontEnd

#59 DCK-20: : Fix issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Need Review
