Repository drupal-ukraine/dcamp-site, pull requests merged in 2019-03, with the labels that each got.

#61 DCK-21: Fix menu click in main menu
  docroot/themes/custom/dckyiv/js/global-menu.js
Labels: Need Review, 🏷 BackEnd

#69 DCK-23: Fix positions and table
  docroot/themes/custom/dckyiv/style/scss/base/_drupal.scss
  docroot/themes/custom/dckyiv/style/scss/base/_layout.scss
  docroot/themes/custom/dckyiv/style/scss/components/_commerce-cart-form.scss
  docroot/themes/custom/dckyiv/style/scss/components/_commerce-checkout-form.scss
  docroot/themes/custom/dckyiv/style/scss/components/_commerce-product-full.scss
  docroot/themes/custom/dckyiv/style/scss/components/_list-as-dropdown.scss
  docroot/themes/custom/dckyiv/style/scss/components/_my-presentations.scss
  docroot/themes/custom/dckyiv/style/scss/components/_node-presentation-form.scss
Labels: Need Review, 🏷 FrontEnd

#62 DCK-21: Small fixes for style
  docroot/themes/custom/dckyiv/style/scss/abstractions/_container.scss
  docroot/themes/custom/dckyiv/style/scss/base/_drupal.scss
  docroot/themes/custom/dckyiv/style/scss/base/_layout.scss
  docroot/themes/custom/dckyiv/style/scss/components/_commerce-cart-form.scss
  docroot/themes/custom/dckyiv/style/scss/components/_footer.scss
  docroot/themes/custom/dckyiv/style/scss/components/_list-as-dropdown.scss
  docroot/themes/custom/dckyiv/style/scss/components/_mobilenav.scss
  docroot/themes/custom/dckyiv/style/scss/components/_my-presentations.scss
  docroot/themes/custom/dckyiv/style/scss/components/_paragraph--camp-products.scss
  docroot/themes/custom/dckyiv/style/scss/components/_paragraph--view-mode--in-wrapper.scss
  docroot/themes/custom/dckyiv/style/scss/components/_paragraph--wrapper-webform.scss
  docroot/themes/custom/dckyiv/style/scss/components/_user_login_form.scss
  docroot/themes/custom/dckyiv/templates/navigation/links--dropbutton--operations.html.twig
Labels: Need Review

#71 DCK-60 Added shopping cart management improvements
  config/sync/language/en/views.view.commerce_cart_form.yml
  config/sync/views.view.commerce_cart_form.yml
  docroot/modules/custom/dckyiv_commerce/dckyiv_commerce.module
  docroot/modules/custom/dckyiv_commerce/src/Plugin/views/field/EditTshirtSize.php
  docroot/themes/custom/dckyiv/style/scss/components/_commerce-cart-form.scss
Labels: Need Review, 🏷 BackEnd, 🏷 FrontEnd

#72 DCK-25: Add CT, View and Paragraph "Sponsor"
  composer.json
  composer.lock
  config/sync/core.base_field_override.node.sponsor.promote.yml
  config/sync/core.base_field_override.node.sponsor.status.yml
  config/sync/core.base_field_override.node.sponsor.title.yml
  config/sync/core.entity_form_display.node.sponsor.default.yml
  config/sync/core.entity_form_display.paragraph.sponsors.default.yml
  config/sync/core.entity_view_display.node.sponsor.default.yml
  config/sync/core.entity_view_display.node.sponsor.teaser.yml
  config/sync/core.entity_view_display.paragraph.sponsors.default.yml
  config/sync/core.extension.yml
  config/sync/field.field.node.sponsor.body.yml
  config/sync/field.field.node.sponsor.field_drupal_org.yml
  config/sync/field.field.node.sponsor.field_facebook.yml
  config/sync/field.field.node.sponsor.field_image.yml
  config/sync/field.field.node.sponsor.field_linkedin.yml
  config/sync/field.field.node.sponsor.field_person.yml
  config/sync/field.field.node.sponsor.field_sponsor_type.yml
  config/sync/field.field.node.sponsor.field_twitter.yml
  config/sync/field.field.node.sponsor.field_web_site.yml
  config/sync/field.field.paragraph.sponsors.field_sponsors.yml
  config/sync/field.storage.node.field_person.yml
  config/sync/field.storage.node.field_sponsor_type.yml
  config/sync/field.storage.node.field_web_site.yml
  config/sync/field.storage.paragraph.field_sponsors.yml
  config/sync/language.content_settings.node.sponsor.yml
  config/sync/language.content_settings.taxonomy_term.sponsor_type.yml
  config/sync/node.type.sponsor.yml
  config/sync/paragraphs.paragraphs_type.sponsors.yml
  config/sync/taxonomy.vocabulary.sponsor_type.yml
  config/sync/views.view.sponsors.yml
Labels: Need Review, 🏷 BackEnd

#74 DCK-27: Override revision form in presentation form
  docroot/modules/custom/dckyiv_core/dckyiv_core.module
Labels: Need Review, 🏷 BackEnd

#77 Notifications update
  config/sync/content_moderation_notifications.content_moderation_notification.approved_candidate.yml
  config/sync/content_moderation_notifications.content_moderation_notification.need_changes.yml
  config/sync/content_moderation_notifications.content_moderation_notification.presentation_has_been_added.yml
  config/sync/content_moderation_notifications.content_moderation_notification.send_my_topic_to_review_author.yml
  config/sync/workflows.workflow.presentation.yml
Labels: Need Review

#81 DCK-29: Fix weight for logout link in user menu
  docroot/modules/custom/dckyiv_user/dckyiv_user.links.task.yml
Labels: Need Review, 🏷 BackEnd
